const generateMathProblems = (count, templates, min, max) => {
    const questions = [];
    for (let i = 0; i < count; i++) {
        const tmpl = templates[i % templates.length];
        let a = Math.floor(Math.random() * (max - min + 1)) + min;
        let b = Math.floor(Math.random() * (max - min + 1)) + min;
        if (a < b) [a, b] = [b, a];
        const data = tmpl(a, b);
        const opts = new Set([data.ans]);
        while (opts.size < 4) opts.add(data.ans + Math.floor(Math.random() * (5 - (-5) + 1)) + (-5));
        questions.push({ id: i, q: data.q, options: Array.from(opts).sort(() => Math.random() - 0.5), answer: data.ans.toString() });
    }
    return questions;
};

const QuestionBank = {
    english: {
        beginner: {
            grammar: [
                ["I ___ a student.", "am", "is", "are", "be"],
                ["She ___ to school every day.", "goes", "go", "going", "gone"],
                ["They ___ playing football now.", "are", "is", "am", "be"],
                ["We ___ lunch yesterday.", "ate", "eat", "eaten", "eating"],
                ["He ___ like apples.", "doesn't", "don't", "not", "isn't"],
                ["My brother ___ tall.", "is", "am", "are", "be"],
                ["___ you like coffee?", "Do", "Does", "Is", "Are"],
                ["She ___ not watching TV.", "is", "does", "do", "has"],
                ["Where ___ you go last night?", "did", "do", "does", "done"],
                ["I have ___ a book.", "read", "reads", "reading", "red"],
                ["This is ___ car.", "my", "mine", "me", "I"],
                ["That book is ___.", "hers", "her", "she", "him"],
                ["___ do you live?", "Where", "What", "Who", "When"],
                ["___ time is it?", "What", "Where", "Who", "Which"],
                ["They ___ friends.", "are", "is", "am", "be"],
                ["We ___ to the park on Sundays.", "go", "goes", "going", "gone"],
                ["___ name is John.", "My", "I", "Me", "Mine"],
                ["He ___ a doctor.", "is", "am", "are", "be"],
                ["I ___ not hungry.", "am", "is", "are", "have"],
                ["She ___ a beautiful dress.", "has", "have", "is", "are"],
                ["___ you speak English?", "Do", "Does", "Is", "Are"],
                ["They ___ happy.", "are", "is", "am", "was"],
                ["The cat is ___ the table.", "under", "in", "at", "to"],
                ["I get up ___ 7 o'clock.", "at", "in", "on", "to"],
                ["She lives ___ London.", "in", "at", "on", "to"],
                ["He is ___ than me.", "taller", "tall", "tallest", "more tall"],
                ["This is the ___ book.", "best", "good", "better", "well"],
                ["I ___ see him tomorrow.", "will", "did", "do", "have"],
                ["Can you ___ me?", "help", "helping", "helps", "helped"],
                ["Please, ___ the door.", "open", "opening", "opens", "opened"],
                ["Don't ___ that.", "do", "does", "doing", "did"],
                ["Where ___ she from?", "is", "are", "am", "do"],
                ["What ___ you doing?", "are", "is", "am", "do"],
                ["I like ___ football.", "playing", "play", "played", "plays"],
                ["She hates ___ early.", "waking up", "wake up", "wakes up", "woke up"],
                ["___ is your favorite color?", "What", "Who", "Where", "When"],
                ["___ is that man?", "Who", "What", "Where", "When"],
                ["I bought ___ apple.", "an", "a", "the", "two"],
                ["She has ___ cat.", "a", "an", "the", "two"],
                ["Look ___ the board.", "at", "in", "on", "to"],
                ["I ___ happy.", "am", "is", "are", "be"],
                ["___ is your name?", "What", "Who", "Where", "Why"],
                ["They ___ students.", "are", "is", "am", "be"],
                ["She ___ a doctor.", "is", "am", "are", "be"],
                ["___ you speak English?", "Do", "Does", "Is", "Are"],
                ["He ___ play football.", "doesn't", "don't", "isn't", "aren't"],
                ["We ___ to school.", "go", "goes", "gone", "going"],
                ["___ he like pizza?", "Does", "Do", "Is", "Are"],
                ["I ___ not tired.", "am", "is", "are", "be"],
                ["___ are you from?", "Where", "Who", "What", "When"],
                ["This is ___ book.", "my", "me", "I", "mine"],
                ["Those ___ my shoes.", "are", "is", "am", "be"],
                ["___ do you live?", "Where", "What", "Who", "When"],
                ["He ___ have a car.", "doesn't", "don't", "isn't", "aren't"],
                ["___ she your sister?", "Is", "Are", "Am", "Do"],
                ["We ___ watching TV.", "are", "is", "am", "do"],
                ["___ they busy?", "Are", "Is", "Am", "Do"],
                ["I ___ have money.", "don't", "doesn't", "isn't", "aren't"],
                ["___ old are you?", "How", "What", "Who", "Where"],
                ["It ___ raining.", "is", "are", "am", "be"],
                ["___ you hungry?", "Are", "Is", "Do", "have"],
                ["She ___ up at 7.", "gets", "get", "got", "getting"],
                ["He ___ breakfast.", "has", "have", "had", "having"],
                ["___ time is it?", "What", "Which", "Who", "Where"],
                ["They ___ not at home.", "are", "is", "am", "do"],
                ["___ is this?", "What", "Who", "Where", "Why"],
                ["I ___ like apples.", "don't", "doesn't", "isn't", "aren't"],
                ["___ we go now?", "Can", "Are", "Is", "Do"],
                ["She ___ swim.", "can", "is", "are", "do"],
                ["___ color is it?", "What", "Who", "Where", "Why"],
                ["Open ___ door.", "the", "a", "an", "two"],
                ["Close ___ book.", "your", "you", "yours", "me"],
                ["___ down, please.", "Sit", "Sat", "Sitting", "Sits"],
                ["___ up, please.", "Stand", "Stood", "Standing", "Stands"],
                ["I ___ a headache.", "have", "has", "am", "is"],
                ["She ___ blue eyes.", "has", "have", "is", "are"],
                ["We ___ a big house.", "have", "has", "are", "is"],
                ["___ you have a pen?", "Do", "Does", "Is", "Are"],
                ["He ___ not have a dog.", "does", "do", "is", "has"],
                ["They ___ got a car.", "have", "has", "are", "is"],
                ["___ she got a sister?", "Has", "Have", "Is", "Does"],
                ["I ___ going to the shop.", "am", "is", "are", "be"],
                ["She ___ reading a book.", "is", "are", "am", "be"],
                ["What ___ you doing?", "are", "is", "am", "do"]
            ],
            vocabulary: [
                ["'Happy' so'zining sinonimini toping:", "Joyful", "Sad", "Angry", "Tired"],
                ["'Big' so'zining teskarisini toping:", "Small", "Huge", "Large", "Tall"],
                ["Oziq-ovqat sotib olinadigan joy:", "Supermarket", "Library", "Gym", "Bank"],
                ["Osmonning rangi qanday?", "Blue", "Green", "Red", "Yellow"],
                ["Hayvonni toping:", "Cat", "Table", "Car", "Phone"],
                ["'Run' fe'lining ma'nosi:", "Yugurmoq", "O'qimoq", "Yozmoq", "Uxlamoq"],
                ["'Green' qaysi rang?", "Yashil", "Qizil", "Ko'k", "Sariq"],
                ["'Teacher' kim?", "O'qituvchi", "Shifokor", "Haydovchi", "Oshpaz"],
                ["'Apple' nima?", "Olma", "Nok", "Uzum", "Anor"],
                ["Dushanba ingliz tilida:", "Monday", "Sunday", "Tuesday", "Friday"],
                ["'Book' so'zining tarjimasini toping:", "Kitob", "Daftar", "Ruchka", "Stol"],
                ["'Mother' so'zining tarjimasini toping:", "Ona", "Ota", "Opasi", "Buvisi"],
                ["'Water' so'zining tarjimasini toping:", "Suv", "Non", "Choy", "Sut"],
                ["'House' so'zining tarjimasini toping:", "Uy", "Maktab", "Bog'", "Do'kon"],
                ["'Dog' so'zining tarjimasini toping:", "It", "Mushuk", "Ot", "Sigir"],
                ["'Red' so'zining tarjimasini toping:", "Qizil", "Oq", "Qora", "Ko'k"],
                ["'Hello' so'zining tarjimasini toping:", "Salom", "Xayr", "Rahmat", "Iltimos"],
                ["'Car' so'zining tarjimasini toping:", "Mashina", "Velosiped", "Avtobus", "Poyezd"],
                ["'Pen' so'zining tarjimasini toping:", "Ruchka", "Qalam", "O'chirg'ich", "Lineyka"],
                ["'One' raqamining tarjimasi:", "Bir", "Ikki", "Uch", "To'rt"],
                ["'Ten' raqamining tarjimasi:", "O'n", "O'ttiz", "Yigirma", "Beshm"],
                ["'Cold' so'zining teskarisi:", "Hot", "Warm", "Cool", "Ice"],
                ["'Fast' so'zining sinonimi:", "Quick", "Slow", "Hard", "Soft"],
                ["'Beautiful' so'zining ma'nosi:", "Chiroyli", "Xunuk", "Katta", "Kichik"],
                ["'To eat' fe'lining ma'nosi:", "Yemoq", "Ichmoq", "Uxlamoq", "Yurmoq"],
                ["'To drink' fe'lining ma'nosi:", "Ichmoq", "Yemoq", "Yuvmoq", "O'ynamoq"],
                ["'Summer' fasli:", "Yoz", "Qish", "Bahor", "Kuz"],
                ["'Winter' fasli:", "Qish", "Yoz", "Bahor", "Kuz"],
                ["'Family' so'zining ma'nosi:", "Oila", "Do'stlar", "Sinf", "Ishxona"],
                ["'Friend' so'zining ma'nosi:", "Do'st", "Dushman", "Qarindosh", "Hamkasb"],
                ["'Bird' so'zining tarjimasi:", "Qush", "Baliq", "It", "Mushuk"],
                ["'Yellow' qaysi rang?", "Sariq", "Yashil", "Qizil", "Ko'k"],
                ["'Table' nima?", "Stol", "Stul", "Eshik", "Deraza"],
                ["'Eye' so'zining ma'nosi:", "Ko'z", "Quloq", "Burun", "Og'iz"],
                ["'Milk' so'zining tarjimasi:", "Sut", "Suv", "Choy", "Sharbat"],
                ["'Monday' qaysi kun?", "Dushanba", "Seshanba", "Chorshanba", "Juma"],
                ["'Sister' kim?", "Singil", "Aka", "Ota", "Ona"],
                ["'Small' so'zining teskarisi:", "Big", "Short", "Long", "Fat"],
                ["'Night' so'zining ma'nosi:", "Tun", "Kun", "Tong", "Kechqurun"],
                ["'Sun' nima?", "Quyosh", "Oy", "Yulduz", "Osmon"],
                ["'Flower' so'zining tarjimasi:", "Gul", "Daraxt", "O't", "Barg"],
                ["'Fish' so'zining tarjimasi:", "Baliq", "Qush", "Ilon", "Qurbaqa"],
                ["'Hand' so'zining ma'nosi:", "Qo'l", "Oyoq", "Bosh", "Yuz"],
                ["'Chair' nima?", "Stul", "Stol", "Divan", "Karavot"],
                ["'White' so'zining tarjimasi:", "Oq", "Qora", "Kulrang", "Jigarrang"],
                ["'Bread' so'zining tarjimasi:", "Non", "Sariyog'", "Pishloq", "Tuxum"],
                ["'Door' so'zining tarjimasi:", "Eshik", "Deraza", "Tom", "Devor"],
                ["'Sad' so'zining teskarisi:", "Happy", "Angry", "Tired", "Hungry"],
                ["'Hot' so'zining teskarisi:", "Cold", "Warm", "Cool", "Dry"],
                ["'Boy' so'zining tarjimasi:", "O'g'il bola", "Qiz bola", "Erkak", "Ayol"],
                ["'Girl' so'zining tarjimasi:", "Qiz bola", "O'g'il bola", "Ayol", "Erkak"],
                ["'Tree' so'zining tarjimasi:", "Daraxt", "Gul", "O't", "Buta"],
                ["'Sky' so'zining ma'nosi:", "Osmon", "Yer", "Dengiz", "Tog'"],
                ["'Moon' nima?", "Oy", "Quyosh", "Yulduz", "Sayyora"],
                ["'Box' so'zining tarjimasi:", "Quti", "Sumka", "Xalta", "Chemodan"],
                ["'Key' so'zining ma'nosi:", "Kalit", "Qulf", "Eshik", "Deraza"],
                ["'Phone' nima?", "Telefon", "Kompyuter", "Radio", "Televizor"],
                ["'Egg' so'zining tarjimasi:", "Tuxum", "Go'sht", "Sut", "Yog'"],
                ["'Meat' so'zining tarjimasi:", "Go'sht", "Non", "Mezva", "Sabzavot"],
                ["'Sugar' so'zining ma'nosi:", "Shakar", "Tuz", "Un", "Guruch"]
            ]
        },
        intermediate: {
            grammar: [
                ["If I ___ you, I would study harder.", "were", "was", "am", "be"],
                ["I have ___ working here for 5 years.", "been", "being", "be", "was"],
                ["She said that she ___ busy.", "was", "is", "were", "are"],
                ["The letter ___ written by John.", "was", "is", "has", "did"],
                ["I look forward to ___ you.", "meeting", "meet", "met", "have met"],
                ["By the time we arrived, the film ___ started.", "had", "has", "was", "is"],
                ["I wish I ___ a car.", "had", "have", "will have", "would have"],
                ["He is interested ___ learning music.", "in", "on", "at", "with"],
                ["She is good ___ math.", "at", "in", "on", "with"],
                ["I prefer tea ___ coffee.", "to", "than", "from", "over"],
                ["Before ___ to bed, I brushed my teeth.", "going", "go", "went", "gone"],
                ["Nobody knows, ___?", "do they", "does he", "doesn't he", "don't they"],
                ["Let's go, ___?", "shall we", "will we", "do we", "let us"],
                ["Neither Tom ___ Mary is here.", "nor", "or", "and", "but"],
                ["Either you ___ leave or I will.", "or", "nor", "and", "but"],
                ["I am used to ___ up early.", "getting", "get", "got", "have got"],
                ["It's no use ___ about it.", "crying", "cry", "to cry", "cries"],
                ["She made him ___ the room.", "clean", "to clean", "cleaning", "cleaned"],
                ["I saw him ___ the street.", "cross", "to cross", "crossed", "crossing"],
                ["You had better ___ a doctor.", "see", "to see", "seeing", "seen"],
                ["I would rather ___ home.", "stay", "to stay", "staying", "stayed"],
                ["Unless you ___, you will fail.", "study", "studied", "will study", "studies"],
                ["As soon as he ___, we will leave.", "arrives", "will arrive", "arrived", "arrive"],
                ["Although it was raining, ___ we went out.", "NO_WORD", "but", "however", "still"],
                ["Despite ___ tired, he kept working.", "being", "be", "was", "is"],
                ["In spite of the ___, we enjoyed it.", "rain", "raining", "rained", "rains"],
                ["It takes 20 minutes ___ to school.", "to get", "getting", "get", "got"],
                ["How long ___ you known him?", "have", "do", "did", "are"],
                ["When I arrived, he ___ dinner.", "was having", "is having", "has", "had"],
                ["While I ___ reading, the phone rang.", "was", "am", "were", "is"],
                ["I will call you when I ___ home.", "get", "will get", "got", "getting"],
                ["She asked me where ___.", "I lived", "do I live", "did I live", "I live"],
                ["If it rains, we ___ go.", "won't", "wouldn't", "didn't", "don't"],
                ["I am looking forward to ___ you.", "seeing", "see", "saw", "seen"],
                ["He used to ___ football.", "play", "playing", "played", "plays"],
                ["I wish I ___ rich.", "were", "am", "was", "will be"],
                ["The car ___ stole was mine.", "which", "who", "where", "what"],
                ["The man ___ I met was nice.", "who", "which", "where", "what"],
                ["She made me ___.", "cry", "crying", "to cry", "cries"],
                ["It is too hot ___ outside.", "to go", "going", "go", "gone"],
                ["I have never ___ sushi.", "eaten", "ate", "eat", "eating"],
                ["Have you ___ beenth to Paris?", "ever", "never", "yet", "just"],
                ["He has been working ___ morning.", "since", "for", "in", "at"],
                ["We have lived here ___ 10 years.", "for", "since", "in", "during"],
                ["By next year, I ___ graduated.", "will have", "have", "had", "will"],
                ["He said he ___ busy.", "was", "is", "will be", "has been"],
                ["She told me ___ wait.", "to", "for", "that", "if"],
                ["I don't know ___ to do.", "what", "that", "which", "how"],
                ["Do you know ___ he is?", "where", "what", "which", "that"],
                ["I stopped ___ to smoke.", "to smoke", "smoking", "smoke", "smoked"],
                ["I remember ___ him.", "meeting", "meet", "to meet", "met"],
                ["Try ___ to sleep.", "to go", "going", "go", "gone"],
                ["Please stop ___ noise.", "making", "to make", "make", "made"],
                ["The cake ___ by mom.", "was made", "made", "is made", "has made"],
                ["Letters ___ delivered daily.", "are", "is", "was", "were"],
                ["The house ___ built in 1990.", "was", "is", "has", "had"],
                ["I ___ my hair cut yesterday.", "had", "have", "has", "did"],
                ["She ___ her car repaired.", "got", "get", "gets", "getting"],
                ["If I had money, I ___ buy it.", "would", "will", "can", "shall"],
                ["If she studies, she ___ pass.", "will", "would", "can", "could"],
                ["I was ___ when I heard the news.", "shocked", "shocking", "shock", "shocks"],
                ["The movie was ___.", "boring", "bored", "bore", "bores"],
                ["I am ___ in history.", "interested", "interesting", "interest", "interests"],
                ["This book is ___.", "interesting", "interested", "interest", "interests"],
                ["I saw him ___ the car.", "drive", "to drive", "driven", "drove"],
                ["She heard them ___.", "talking", "talked", "to talk", "talks"],
                ["I let him ___ my phone.", "use", "to use", "using", "used"],
                ["He made her ___.", "smile", "to smile", "smiling", "smiled"],
                ["I would rather ___ tea.", "drink", "to drink", "drinking", "drank"]
            ],
            vocabulary: [
                ["'Give up' iborasining ma'nosi:", "Quit", "Start", "Continue", "Jump"],
                ["'Difficult' so'zining sinonimi:", "Challenging", "Easy", "Simple", "Basic"],
                ["Qo'lga nima kiyiladi?", "Gloves", "Socks", "Hats", "Shoes"],
                ["Binolarni loyihalashtiradigan shaxs:", "Architect", "Doctor", "Chef", "Pilot"],
                ["'Put off' iborasining ma'nosi:", "Postpone", "Cancel", "Start", "Finish"],
                ["'Depend on' iborasining ma'nosi:", "Rely on", "Ignore", "Leave", "Make"],
                ["'Ancient' so'zining teskarisi:", "Modern", "Old", "Antique", "Past"],
                ["'Wealthy' so'zining sinonimi:", "Rich", "Poor", "Need", "Sad"],
                ["'Invention' so'zining ma'nosi:", "Ixtiro", "Sayohat", "Urush", "Tinchlik"],
                ["'Environment' so'zining ma'nosi:", "Atrof-muhit", "Kosmos", "Dengiz", "Shahar"],
                ["'Develop' so'zining tarjimasini toping:", "Rivojlanmoq", "To'xtamoq", "Yashamoq", "O'lmoq"],
                ["'Opportunity' so'zining tarjimasini toping:", "Imkoniyat", "Muammo", "Vaqt", "Pul"],
                ["'Success' so'zining tarjimasini toping:", "Muvaffaqiyat", "Mag'lubiyat", "Omad", "Baxt"],
                ["'Available' so'zining tarjimasini toping:", "Mavjud", "Band", "Yo'q", "Qimmat"],
                ["'Condition' so'zining ma'nosi:", "Sharoit", "Uy", "Maktab", "Yo'l"],
                ["'Necessary' so'zining ma'nosi:", "Zarur", "Keraksiz", "Oson", "Qiyin"],
                ["'Improve' so'zining ma'nosi:", "Yaxshilamoq", "Buzmoq", "O'zgartirmoq", "Sotmoq"],
                ["'Decision' so'zining ma'nosi:", "Qaror", "Fikr", "O'y", "Orzu"],
                ["'Protect' so'zining ma'nosi:", "Himoya qilmoq", "Hujum qilmoq", "Qochmoq", "Yashirinmoq"],
                ["'Pollution' so'zining ma'nosi:", "Ifloslanish", "Tozalik", "Suv", "Havo"],
                ["'Dangerous' so'zining sinonimi:", "Risky", "Safe", "Calm", "Slow"],
                ["'Purchase' so'zining sinonimi:", "Buy", "Sell", "Give", "Take"],
                ["'Vacation' so'zining ma'nosi:", "Ta'til", "Ish", "O'qish", "Kasal"],
                ["'Foreign' so'zining ma'nosi:", "Xorijiy", "Mahalliy", "Yangi", "Eski"],
                ["'Traditional' so'zining ma'nosi:", "An'anaviy", "Zamonaviy", "Kelajak", "O'tmish"],
                ["'Celebrate' so'zining ma'nosi:", "Nishonlamoq", "Yig'lamoq", "Ishlamoq", "Uxlamoq"],
                ["'Crowded' so'zining ma'nosi:", "Gavjum", "Bo'sh", "Keng", "Tor"],
                ["'Expensive' so'zining teskarisi:", "Cheap", "Costly", "High", "Low"],
                ["'Noisy' so'zining teskarisi:", "Quiet", "Loud", "Big", "Small"],
                ["'Anxious' so'zining sinonimi:", "Worried", "Happy", "Calm", "Brave"],
                ["'To complain' ma'nosi:", "Shikoyat qilmoq", "Maqtamoq", "Yordam bermoq", "Ketmoq"],
                ["'To suggest' ma'nosi:", "Taklif qilmoq", "Rad etmoq", "Qabul qilmoq", "Bajarmoq"],
                ["'Curious' so'zining ma'nosi:", "Qiziqqon", "Zerikarli", "Aqlli", "Tentak"],
                ["'Generous' so'zining ma'nosi:", "Saxiy", "Xasis", "Boy", "Kambag'al"],
                ["'Stubborn' so'zining ma'nosi:", "Qaysar", "Yuvosh", "Aqlli", "Tez"],
                ["'Polite' so'zining teskarisi:", "Rude", "Nice", "Kind", "Good"],
                ["'Safe' so'zining teskarisi:", "Dangerous", "Secure", "Calm", "Easy"],
                ["'Empty' so'zining teskarisi:", "Full", "Hollow", "Big", "Small"],
                ["'To invent' ma'nosi:", "Ixtiro qilmoq", "Kashf qilmoq", "Topmoq", "Yo'qotmoq"],
                ["'To discover' ma'nosi:", "Kashf qilmoq", "Yaratmoq", "O'ylamoq", "Yozmoq"],
                ["'Solution' so'zining ma'nosi:", "Yechim", "Muammo", "Savol", "Javob"],
                ["'Reason' so'zining ma'nosi:", "Sabab", "Natija", "Maqsad", "Yo'l"],
                ["'Advice' so'zining ma'nosi:", "Maslahat", "Buyruq", "Fikr", "Jazo"],
                ["'Behavior' so'zining ma'nosi:", "Xulq-atvor", "Muomala", "Gapirish", "Yurish"],
                ["'Opinion' so'zining ma'nosi:", "Fikr", "Haqiqat", "Yolg'on", "Bilim"],
                ["'Available' sinonimi:", "Accessible", "Busy", "Free", "Open"],
                ["'Huge' sinonimi:", "Enormous", "Tiny", "Small", "Little"],
                ["'To refuse' ma'nosi:", "Rad etmoq", "Qabul qilmoq", "So'ramoq", "Bermoq"],
                ["'To accept' ma'nosi:", "Qabul qilmoq", "Rad etmoq", "Olish", "Berish"],
                ["'To remind' ma'nosi:", "Eslatmoq", "Unutmoq", "O'ylamoq", "Bilmoq"],
                ["'To forget' ma'nosi:", "Unutmoq", "Eslamoq", "Bilmoq", "Ko'rmoq"],
                ["'Guest' so'zining ma'nosi:", "Mehmon", "Mezbon", "Do'st", "Dushman"],
                ["'Owner' so'zining ma'nosi:", "Ega", "Mehmon", "Sotuvchi", "Mijoz"],
                ["'Customer' so'zining ma'nosi:", "Mijoz", "Sotuvchi", "Rahbar", "Ishchi"],
                ["'Employee' so'zining ma'nosi:", "Xodim", "Rahbar", "Direktor", "Mijoz"],
                ["'Employer' so'zining ma'nosi:", "Ish beruvchi", "Ishchi", "Xodim", "Talaba"],
                ["'Salary' so'zining ma'nosi:", "Oylik maosh", "Narx", "Pul", "Soliq"],
                ["'Price' so'zining ma'nosi:", "Narx", "Pul", "Qiymat", "Sifat"],
                ["'Discount' so'zining ma'nosi:", "Chegirma", "Narx", "Foyda", "Zarar"]
            ]
        },
        advanced: {
            grammar: [
                ["Had I known, I ___ have come.", "would", "will", "did", "can"],
                ["Not only ___ smart, but he is also kind.", "is he", "he is", "he was", "was he"],
                ["It's high time you ___ to bed.", "went", "go", "gone", "going"],
                ["She suggested that he ___ a doctor.", "see", "sees", "saw", "seen"],
                ["Seldom ___ we see such beauty.", "do", "did", "have", "are"],
                ["No sooner ___ I arrived than he left.", "had", "have", "did", "was"],
                ["Under no circumstances ___ you open this door.", "should", "would", "could", "might"],
                ["Little ___ he know about the surprise.", "did", "does", "has", "is"],
                ["Were I to go, I ___ tell you.", "would", "will", "can", "should"],
                ["Only after ___ the book did I understand.", "reading", "read", "reads", "have read"],
                ["Barely ___ I started speaking when needed.", "had", "have", "was", "did"],
                ["The more you learn, the more you ___.", "know", "knew", "knowing", "known"],
                ["She acts as if she ___ rich.", "were", "is", "was", "will be"],
                ["Suppose you ___ the lottery, what would you do?", "won", "win", "will win", "winning"],
                ["Unless I ___ mistaken, that's John.", "am", "be", "was", "weren't"],
                ["He needs to have his car ___.", "repaired", "repair", "repairing", "to repair"],
                ["I got him ___ the car.", "to wash", "wash", "washing", "washed"],
                ["She accused him ___ stealing the money.", "of", "for", "on", "about"],
                ["He congratulated me ___ passing the exam.", "on", "for", "of", "about"],
                ["She insisted ___ paying for dinner.", "on", "in", "at", "for"],
                ["I apologize ___ being late.", "for", "of", "in", "to"],
                ["He succeeded ___ solving the problem.", "in", "on", "at", "of"],
                ["I am capable ___ doing this.", "of", "for", "in", "at"],
                ["She is afraid ___ dogs.", "of", "at", "in", "on"],
                ["He is famous ___ his paintings.", "for", "of", "in", "at"],
                ["Having ___ the work, he went home.", "finished", "finish", "finishing", "finishes"],
                ["Never ___ I seen such a thing.", "have", "do", "did", "has"],
                ["So tired ___ he that he fell asleep.", "was", "is", "were", "been"],
                ["Such ___ the power of the storm.", "was", "were", "is", "are"],
                ["Hardly ___ I arrived when he left.", "had", "have", "did", "was"],
                ["Scarcely ___ the game started when it rained.", "had", "did", "have", "was"],
                ["Should you ___ help, call me.", "need", "needs", "needed", "will need"],
                ["Had it not been for his help, I ___ failed.", "would have", "will have", "had", "would"],
                ["I ___ rather you didn't smoke.", "would", "had", "will", "should"],
                ["It's time we ___ home.", "went", "go", "gone", "going"],
                ["I prefer coffee ___ tea.", "to", "than", "from", "over"],
                ["He is accustomed ___ living alone.", "to", "with", "in", "at"],
                ["She objected ___ being called late.", "to", "for", "on", "at"],
                ["He confessed ___ the money.", "to stealing", "steal", "stealing", "stole"],
                ["I look forward ___ hearing from you.", "to", "for", "at", "in"],
                ["She is devoted ___ her job.", "to", "for", "in", "at"],
                ["He was accused ___ theft.", "of", "for", "on", "in"],
                ["She was convicted ___ murder.", "of", "for", "in", "on"],
                ["I am fed up ___ this weather.", "with", "of", "about", "for"],
                ["He is fond ___ music.", "of", "in", "at", "on"],
                ["She is keen ___ tennis.", "on", "in", "at", "of"],
                ["I am bad ___ cooking.", "at", "in", "on", "with"],
                ["He is good ___ math.", "at", "in", "on", "with"],
                ["I am proud ___ you.", "of", "for", "in", "at"],
                ["She is ashamed ___ her behavior.", "of", "for", "in", "at"],
                ["He is dependent ___ his parents.", "on", "in", "at", "to"],
                ["I am independent ___ my family.", "of", "from", "to", "in"],
                ["She is jealous ___ her sister.", "of", "for", "in", "at"],
                ["He is envious ___ my success.", "of", "for", "in", "at"],
                ["I am suspicious ___ him.", "of", "for", "in", "at"],
                ["She is conscious ___ her health.", "of", "for", "in", "at"],
                ["He is aware ___ the danger.", "of", "for", "in", "at"],
                ["I am capable ___ doing it.", "of", "for", "in", "at"],
                ["She is guilty ___ the crime.", "of", "for", "in", "at"],
                ["It is essential that he ___ here on time.", "be", "is", "was", "were"],
                ["I suggest that she ___ a doctor.", "see", "sees", "saw", "must see"],
                ["It is important that you ___ quiet.", "keep", "keeps", "kept", "keeping"],
                ["I insist that he ___ immediately.", "leave", "leaves", "left", "leaving"],
                ["If need ___ , I will help you.", "be", "is", "was", "are"],
                ["Suffice it to ___ that he refused.", "say", "saying", "said", "says"],
                ["Be that as it ___.", "may", "might", "can", "could"],
                ["Come what ___.", "may", "might", "can", "could"],
                ["God ___ the Queen!", "save", "saves", "saved", "saving"],
                ["Long ___ the King!", "live", "lives", "lived", "living"]
            ],
            vocabulary: [
                ["'Ubiquitous' so'zining ma'nosi:", "Everywhere", "Rare", "Unique", "Hidden"],
                ["'Ephemeral' so'zining ma'nosi:", "Short-lived", "Eternal", "Long", "Permanent"],
                ["'Pragmatic' so'zining sinonimi:", "Practical", "Theoretical", "Dreamy", "Foolish"],
                ["'Break the ice' iborasi:", "Start conversation", "Break something", "Be cold", "Leave"],
                ["'Serendipity' so'zining ma'nosi:", "Happy accident", "Bad luck", "Planning", "Sorrow"],
                ["'Obsolete' so'zining ma'nosi:", "Outdated", "New", "Fresh", "Current"],
                ["'Magnanimous' so'zining ma'nosi:", "Generous", "Selfish", "Small", "Tiny"],
                ["'Meticulous' so'zining sinonimi:", "Careful", "Careless", "Fast", "Lazy"],
                ["'To alleviate' fe'lining ma'nosi:", "To lessen", "To increase", "To worsen", "To stop"],
                ["'To scrutinize' fe'lining ma'nosi:", "To examine", "To ignore", "To glance", "To skim"],
                ["'Ambiguous' so'zining ma'nosi:", "Ikki ma'noli", "Aniq", "Oddiy", "Qiyin"],
                ["'Inevitable' so'zining ma'nosi:", "Muqarrar", "Kutilmagan", "Mumkin", "Ehtimoliy"],
                ["'To procrastinate' ma'nosi:", "Keyinga qoldirmoq", "Bajarmoq", "Tezlashmoq", "Unutmoq"],
                ["'Eloquent' so'zining ma'nosi:", "Notiq", "Jim", "Qo'pol", "Yozma"],
                ["'Nostalgia' ma'nosi:", "Sog'inch", "Nafrat", "Kelajak", "Unutish"],
                ["'Paradox' ma'nosi:", "Ziddiyat", "Haqiqat", "Yolg'on", "Hikoya"],
                ["'To fluctuate' ma'nosi:", "O'zgarib turmoq", "Barqaror bo'lmoq", "O'smoq", "Tushmoq"],
                ["'To implement' ma'nosi:", "Joriy etmoq", "Rad etmoq", "O'ylamoq", "Yozmoq"],
                ["'Hypothesis' tarjimasi:", "Faraz", "Haqiqat", "Qoida", "Qonun"],
                ["'Subtle' so'zining ma'nosi:", "Nozik", "Dag'al", "Ochiq", "Yorqin"],
                ["'Candid' so'zining sinonimi:", "Honest", "Lying", "Hidden", "Fake"],
                ["'Lethargic' so'zining sinonimi:", "Tired", "Energetic", "Fast", "Happy"],
                ["'Benevolent' so'zining teskarisi:", "Malevolent", "Kind", "Good", "Nice"],
                ["'Vague' so'zining teskarisi:", "Clear", "Unclear", "Dark", "Foggy"],
                ["'A piece of cake' iborasi:", "Very easy", "Very hard", "Tasty food", "Dessert"],
                ["'To bite the bullet' iborasi:", "To endure pain", "To eat bullet", "To shoot", "To die"],
                ["'Break a leg' iborasi:", "Good luck", "Bad luck", "Hurt leg", "Hospital"],
                ["'To hit the sack' iborasi:", "To sleep", "To hit bag", "To work", "To eat"],
                ["'Under the weather' iborasi:", "Sick", "Raining", "Sunny", "Happy"],
                ["'Spill the beans' iborasi:", "Reveal secret", "Drop food", "Cook beans", "Eat beans"],
                ["'Once in a blue moon' iborasi:", "Rarely", "Often", "Never", "Always"],
                ["'To burn bridges' iborasi:", "Cut ties", "Fire", "Build", "Travel"],
                ["'To cut corners' iborasi:", "Do cheaply/badly", "Cut paper", "Turn corner", "Drive fast"],
                ["'To miss the boat' iborasi:", "Too late", "Miss trip", "Swim", "Sail"],
                ["'Through thick and thin' iborasi:", "In all times", "Fat and skinny", "Hard and soft", "Weather"],
                ["'To sit on the fence' iborasi:", "Undecided", "Sit outside", "Watch", "Play"],
                ["'To add insult to injury' iborasi:", "Worsen situation", "Hurt", "Help", "Cure"],
                ["'To beat around the bush' iborasi:", "Avoid topic", "Hit bush", "Gardening", "Walking"],
                ["'Better late than never' iborasi:", "Better eventually", "Late is bad", "Never come", "Time"],
                ["'To call it a day' iborasi:", "Stop working", "Call friend", "Day time", "Night"],
                ["'To hang in there' iborasi:", "Don't give up", "Hang clothes", "Wait", "Stop"],
                ["'To get out of hand' iborasi:", "Out of control", "Hand injury", "Drop", "Leave"],
                ["'To pull someone's leg' iborasi:", "Joke/Tease", "Hurt leg", "Help walk", "Dance"],
                ["'To make ends meet' iborasi:", "Survive financially", "Join lines", "Meet people", "Finish work"],
                ["'To wrap your head around' iborasi:", "Understand", "Wear hat", "Headache", "Sleep"],
                ["'To give the cold shoulder' iborasi:", "Ignore", "Cold body", "Hug", "Hit"],
                ["'To see eye to eye' iborasi:", "Agree", "Stare", "Fight", "Look"],
                ["'To let the cat out of the bag' iborasi:", "Reveal secret", "Free cat", "Buy cat", "Lost cat"],
                ["'To kill two birds with one stone' iborasi:", "Two goals/one action", "Hunting", "Cooking", "Flying"],
                ["'To cost an arm and a leg' iborasi:", "Expensive", "Cheap", "Body parts", "Injury"],
                ["'To feel under the weather' iborasi:", "Sick", "Sad", "Happy", "Tired"],
                ["'To crying over spilled milk' iborasi:", "Regret past", "Clean milk", "Drink milk", "Buy milk"],
                ["'To bark up the wrong tree' iborasi:", "Wrong assumption", "Dog barking", "Climb tree", "Gardening"],
                ["'To judge a book by its cover' iborasi:", "Judge by appearance", "Read book", "Buy book", "Write book"],
                ["'To hit the nail on the head' iborasi:", "Exactly right", "Carpenter", "Hurt head", "Build"]
            ]
        }
    },
    iq: {
        beginner: [
            { q: "5, 10, 15, 20, ...?", options: ["22", "24", "25", "30"], answer: "25", explanation: "Har bir son 5 taga ortib bormoqda.", motivation: "Ajoyib boshlanish!" },
            { q: "Qaysi biri ortiqcha? 2, 4, 8, 9, 16", options: ["2", "8", "9", "16"], answer: "9", explanation: "9 toq son, qolganlari juft sonlar.", motivation: "Juda yaxshi, davom eting!" },
            { q: "A + B = 10, A = 6, B = ?", options: ["2", "4", "6", "8"], answer: "4", explanation: "10 - 6 = 4.", motivation: "Hisoblash qobiliyatingiz zo'r!" },
            { q: "Dushanba, Seshanba, Chorshanba, ...?", options: ["Juma", "Payshanba", "Shanba", "Yakshanba"], answer: "Payshanba", explanation: "Hafta kunlari ketma-ketligi.", motivation: "Mantiqiy fikrlashingiz joyida!" },
            { q: "1, 1, 2, 3, 5, 8, ...?", options: ["11", "12", "13", "14"], answer: "13", explanation: "Fibonachchi ketma-ketligi: oldingi ikki son yig'indisi (5+8=13).", motivation: "Qiyin savol edi, qoyil!" },
            { q: "Qaysi shakl 3 burchakli?", options: ["Kvadrat", "Uchburchak", "Doira", "Tortburchak"], answer: "Uchburchak", explanation: "Nomidan ko'rinib turibdi.", motivation: "Oddiy va aniq!" },
            { q: "Qaysi biri ortiqcha?", options: ["Stol", "Stul", "Shkaf", "Olma"], answer: "Olma", explanation: "Olma meva, qolganlari mebel.", motivation: "To'g'ri!" },
            { q: "10, 20, 30, ...?", options: ["35", "40", "50", "60"], answer: "40", explanation: "10 taga ortib boryapti.", motivation: "Juda oddiy!" },
            { q: "Bugun Dushanba bo'lsa, 2 kundan keyin nima?", options: ["Chorshanba", "Payshanba", "Juma", "Seshanba"], answer: "Chorshanba", explanation: "Dushanba -> Seshanba -> Chorshanba.", motivation: "Vaqtni bilasiz!" },
            { q: "Qaysi biri yumaloq?", options: ["Kitob", "To'p", "G'isht", "Televizor"], answer: "To'p", explanation: "To'p shakli shar.", motivation: "Geometriya!" },
            { q: "2 + 2 * 2 = ?", options: ["6", "8", "4", "10"], answer: "6", explanation: "Avval ko'paytirish: 2*2=4, keyin qo'shish: 2+4=6.", motivation: "Matematik qoida!" },
            { q: "Yilning birinchi oyi?", options: ["Yanvar", "Fevral", "Mart", "Dekabr"], answer: "Yanvar", explanation: "Yil boshi.", motivation: "To'g'ri!" },
            { q: "Qaysi qush ucha olmaydi?", options: ["Qarles", "Pingvin", "Burgut", "Kabutar"], answer: "Pingvin", explanation: "Pingvinlar suzadi, uchmaydi.", motivation: "Biologiya!" },
            { q: "Suv qachon muzlaydi?", options: ["0 gradus", "100 gradus", "10 gradus", "-100 gradus"], answer: "0 gradus", explanation: "Muzlash nuqtasi.", motivation: "Fizika!" },
            { q: "Qaysi oyda 28 kun bor?", options: ["Hammasida", "Fevralda", "Yanvarda", "Martda"], answer: "Hammasida", explanation: "Hamma oyda kamida 28 kun bor.", motivation: "Mantiqiy tuzoq!" },
            { q: "Stolda 3 ta olma bor edi. Siz 2 tasini oldingiz. Sizda nechta olma bor?", options: ["2 ta", "1 ta", "3 ta", "0 ta"], answer: "2 ta", explanation: "Siz olganingiz o'zingizda qoladi.", motivation: "Diqqatli bo'ling!" },
            { q: "Qaysi so'z hamma lug'atlarda xato yozilgan?", options: ["Xato", "Lug'at", "To'g'ri", "Kitob"], answer: "Xato", explanation: "'Xato' so'zi har doim 'Xato' deb yoziladi.", motivation: "So'z o'yini!" },
            { q: "Yomg'irda kimning sochi ho'l bo'lmaydi?", options: ["Kal odamning", "Soyabonli odamning", "Uyda o'tirgan odamning", "Hamma javob to'g'ri"], answer: "Hamma javob to'g'ri", explanation: "Mantiqan hammasi to'g'ri bo'lishi mumkin, lekin klassik javob 'Kal'. Aslida soyabon va uy ham to'g'ri.", motivation: "Topqirlik!" },
            { q: "Nimani sindirmasdan ishlatib bo'lmaydi?", options: ["Tuxum", "Qoshiq", "Stol", "Suv"], answer: "Tuxum", explanation: "Qovurish uchun sindirish kerak.", motivation: "Oddiy haqiqat!" },
            { q: "U sizniki, lekin boshqalar uni sizdan ko'ra ko'proq ishlatadi. Bu nima?", options: ["Ismingiz", "Pulingiz", "Telefoningiz", "Uyingiz"], answer: "Ismingiz", explanation: "Boshqalar sizni chaqirish uchun ishlatadi.", motivation: "Mashhur topishmoq!" },
            { q: "Qaysi qo'l bilan choyni aralashtirish qulayroq?", options: ["Qoshiq bor qo'l bilan", "O'ng qo'l", "Chap qo'l", "Ikkala qo'l"], answer: "Qoshiq bor qo'l bilan", explanation: "Qo'l bilan emas, qoshiq bilan aralashtiriladi!", motivation: "Hazil-mutoyiba!" },
            { q: "Dunyodagi eng katta okean?", options: ["Tinch okeani", "Atlantika", "Hind", "Shimoliy Muz"], answer: "Tinch okeani", explanation: "Geografiya.", motivation: "Bilimdon!" },
            { q: "O'zbekiston poytaxti?", options: ["Toshkent", "Samarqand", "Buxoro", "Xiva"], answer: "Toshkent", explanation: "Aniq fakt.", motivation: "Vatanparvar!" }
        ],
        intermediate: [
            { q: "1, 4, 9, 16, 25, ...?", options: ["30", "32", "36", "40"], answer: "36", explanation: "Kvadrat sonlar: 1^2, 2^2, 3^2, 4^2, 5^2, 6^2=36.", motivation: "Mukammal mantiq!" },
            { q: "Barcha gullar o'simlik. Atirgul - gul. Xulosa?", options: ["Atirgul o'simlik", "Atirgul qizil", "O'simliklar gul", "Xulosa yo'q"], answer: "Atirgul o'simlik", explanation: "Umumiy qoidadan xususiy xulosa.", motivation: "Deduktiv fikrlash a'lo!" },
            { q: "Soat 12:00 da minut va soat millari ustma-ust tushadi. Soat 6:00 da-chi?", options: ["Ustma-ust", "Qarama-qarshi", "90 gradus", "Bilmayman"], answer: "Qarama-qarshi", explanation: "6:00 da soat mili 6 da, minut mili 12 da bo'ladi.", motivation: "Tasavvur qobiliyatingiz kuchli!" },
            { q: "OT - 2, IT - 2, BUQA - 4, ECHKI - ?", options: ["2", "3", "4", "5"], answer: "5", explanation: "Harflar soni: E-C-H-K-I = 5 ta.", motivation: "Kuzatuvchanlik zo'r!" },
            { q: "Ota 30 yoshda, o'g'il 5 yoshda. Necha yildan keyin ota o'g'ildan 2 marta katta bo'ladi?", options: ["10", "15", "20", "25"], answer: "20", explanation: "20 yildan keyin: Ota 50, o'g'il 25 (50=25*2).", motivation: "Matematik mantiq ajoyib!" },
            { q: "Qora, Oq, Qizil, Yashil. Ortiqchasi?", options: ["Qora", "Oq", "Qizil", "Yashil"], answer: "Yashil", explanation: "Yashil - asosiy rang emas (aralashma), yoki boshqa mantiq bo'lysis mumkin, lekin ko'pincha bu oddiy ajratish.", motivation: "Rang ajratish qobiliyati yaxshi!" },
            { q: "Qo'l : Barmoq = Oyoq : ...?", options: ["Barmoq", "Tizza", "Tovon", "Etik"], answer: "Barmoq", explanation: "Qo'lda barmoq bor, oyoqda ham.", motivation: "Analogiya!" },
            { q: "A=1, B=2, C=3. CAB = ?", options: ["312", "123", "321", "213"], answer: "312", explanation: "C=3, A=1, B=2.", motivation: "Kodlash!" },
            { q: "1, 2, 4, 8, ...?", options: ["10", "12", "14", "16"], answer: "16", explanation: "Har safar 2 ga ko'paymoqda.", motivation: "Progressiya!" },
            { q: "Akamning otasi menga kim?", options: ["Ota", "Tog'a", "Amaki", "Bobo"], answer: "Ota", explanation: "Aka-uka bitta ota-onadan.", motivation: "Qarindoshlik!" },
            { q: "Qaysi so'z palindrom (ters o'qilsa ham bir xil)?", options: ["Kiyik", "Kitob", "Qalam", "Daftar"], answer: "Kiyik", explanation: "K-i-y-i-k = K-i-y-i-k.", motivation: "So'z o'yini!" },
            { q: "Elektr lampochkani kim ixtiro qilgan?", options: ["Edison", "Tesla", "Nyuton", "Eynshteyn"], answer: "Edison", explanation: "Tomas Edison.", motivation: "Tarixiy fakt!" },
            { q: "1, 3, 6, 10, 15, ...?", options: ["21", "20", "25", "18"], answer: "21", explanation: "Qo'shilib borish: +2, +3, +4, +5, +6. 15+6=21.", motivation: "Matematik ketma-ketlik!" },
            { q: "Qaysi oyda insonlar eng kam ovqatlanadi?", options: ["Fevral", "Ramazon", "Yanvar", "Dekabr"], answer: "Fevral", explanation: "Chunki unda kunlar soni eng kam (28/29).", motivation: "Mantiqiy statistika!" },
            { q: "Avtobusda 10 kishi bor. Bekatda 5 kishi tushdi, 3 kishi chiqdi. Haydovchining ko'zi qanday rangda?", options: ["Bilmayman", "Qora", "Ko'k", "Yashil"], answer: "Bilmayman", explanation: "Savol shartida haydovchi haqida ma'lumot yo'q.", motivation: "E'tiborli bo'ling!" },
            { q: "Nimani yerdan ko'tarish oson, lekin uloqtirish qiyin?", options: ["Parranda pati", "Tosh", "Temir", "Yog'och"], answer: "Parranda pati", explanation: "Yengil, shuning uchun uzoqqa otib bo'lmaydi.", motivation: "Fizika qonuni!" },
            { q: "U yurmaydi, lekin har doim yo'lda turadi. Bu nima?", options: ["Svetofor", "Mashina", "Poyezd", "Samolyot"], answer: "Svetofor", explanation: "Yo'l harakatini tartiblaydi.", motivation: "To'g'ri!" },
            { q: "Qaysi savolga hech qachon 'ha' deb javob berib bo'lmaydi?", options: ["Uxlab yotibsizmi?", "Tirikmisiz?", "Ochsizmi?", "Kasalmisiz?"], answer: "Uxlab yotibsizmi?", explanation: "Agar uxlayotgan bo'lsangiz, javob berolmaysiz.", motivation: "Paradoks!" },
            { q: "Odamda bitta, qarg'ada ikkita, ayiqda yo'q. Bu nima?", options: ["'R' harfi", "Qanot", "Oyoq", "Tumshuq"], answer: "'R' harfi", explanation: "So'z tarkibidagi harf.", motivation: "Tilshunoslik!" },
            { q: "Dengizda qanday toshlar bo'lmaydi?", options: ["Quruq", "Suvli", "Katta", "Kichik"], answer: "Quruq", explanation: "Dengizdagi hamma narsa ho'l bo'ladi.", motivation: "Oddiy mantiq!" },
            { q: "Bir xonada 4 ta mushuk bor. Har bir mushukning qarshisida 3 ta mushuk o'tiribdi. Jami nechta mushuk bor?", options: ["4 ta", "12 ta", "3 ta", "16 ta"], answer: "4 ta", explanation: "To'rtburchak shaklida o'tiribdi.", motivation: "Fazoviy tasavvur!" }
        ],
        advanced: [
            { q: "2, 6, 12, 20, 30, ...?", options: ["36", "40", "42", "48"], answer: "42", explanation: "Ketma-ketlik: 1*2, 2*3, 3*4, 4*5, 5*6, 6*7=42.", motivation: "Oliy darajadagi mantiq!" },
            { q: "VR, YQ, ZP, ...?", options: ["AO", "BO", "CO", "DO"], answer: "AO", explanation: "Alifbo tartibi bo'yicha teskari va to'g'ri siljish.", motivation: "Harflar bilan ishlash a'lo!" },
            { q: "Agar kecha ertadan keyin bo'lganida, bugun yakshanba bo'lardi. Bugun qaysi kun?", options: ["Juma", "Shanba", "Yakshanba", "Dushanba"], answer: "Juma", explanation: "Bu klassik vaqt topishish masalasi.", motivation: "Vaqtni zo'r his qilasiz!" },
            { q: "888 + 88 + ? = 1000", options: ["8", "16", "24", "88"], answer: "24", explanation: "888 + 88 = 976. 1000 - 976 = 24.", motivation: "Tezkor hisob!" },
            { q: "Shifokorga 3 ta tabletka berildi. Har yarim soatda bittadan ichish kerak. Qancha vaqt ketadi?", options: ["1.5 soat", "1 soat", "2 soat", "3 soat"], answer: "1 soat", explanation: "1-sini hozir, 2-sini 30 min keyin, 3-sini 60 min keyin. Jami 1 soat.", motivation: "E'tiborlisiz!" },
            { q: "Uyning 4 tomoni janubga qaraydi. Ayiq qanday rangda?", options: ["Oq", "Qora", "Jigarrang", "Kulrang"], answer: "Oq", explanation: "Faqat Shimoliy qutbda hamma tomon janubga qaraydi. Ayiq oq.", motivation: "Geografik mantiq zo'r!" },
            { q: "Ertaga kecha bo'lganida edi, bugun payshanba bo'lardi. Bugun qaysi kun?", options: ["Shanba", "Juma", "Yakshanba", "Dushanba"], answer: "Shanba", explanation: "Mantiqiy vaqt o'yini.", motivation: "Vaqt ustasi!" },
            { q: "Siz musobaqada ikkinchi o'rindagi odamdan o'zib ketdingiz. Nechinchi o'rindasiz?", options: ["Ikkinchi", "Birinchi", "Uchinchi", "To'rtinchi"], answer: "Ikkinchi", explanation: "Ikkinchi o'rnini egallaysiz.", motivation: "Klassik xato!" },
            { q: "Siz musobaqada oxirgi o'rindagi odamdan o'zib ketdingiz. Nechinchi o'rindasiz?", options: ["Imkonsiz", "Oxirgi", "Oxirgisidan oldingi", "Birinchi"], answer: "Imkonsiz", explanation: "Oxirgi odamdan o'zib bo'lmaydi, chunki uning orqasida hech kim yo'q.", motivation: "Diqqat!" },
            { q: "Ota va o'g'il birgalikda 110 yoshda. Ota o'g'ildan 100 yosh katta. O'g'il necha yoshda?", options: ["5", "10", "15", "1"], answer: "5", explanation: "x + (x+100) = 110 -> 2x = 10 -> x = 5. Ota 105 yosh.", motivation: "Algebraik mantiq!" },
            { q: "8 ta 8 dan 1000 hosil qiling.", options: ["888+88+8+8+8", "888+88+88", "8x8x8+8", "8888/8"], answer: "888+88+8+8+8", explanation: "Yig'indi 1000 ga teng.", motivation: "Matematik o'yin!" },
            { q: "Qaysi idishni to'ldirib bo'lmaydi?", options: ["Teshik", "Katta", "Kichik", "Suvli"], answer: "Teshik", explanation: "Tubi yo'q idish.", motivation: "Mantiqiy yechim!" },
            { q: "Qora dengizga tushgan oq tosh nima bo'ladi?", options: ["Ho'l bo'ladi", "Cho'kadi", "Oqaradi", "Yo'qoladi"], answer: "Ho'l bo'ladi", explanation: "Birinchi navbatda ho'l bo'ladi.", motivation: "Oddiy haqiqat!" },
            { q: "U gapiradi, lekin og'zi yo'q. Eshitadi, lekin qulog'i yo'q. Bu nima?", options: ["Aks-sado (Exo)", "Telefon", "Radio", "Televizor"], answer: "Aks-sado (Exo)", explanation: "Tabiat hodisasi.", motivation: "Poetik topishmoq!" },
            { q: "Qaysi uydan chiqib bo'lmaydi?", options: ["Tamg'a (Peчать)", "Qamoqxona", "Labirint", "Orol"], answer: "Tamg'a (Peчать)", explanation: "Rus tilida 'dom - pechat'. Hazil savol.", motivation: "Topqirlik!" }
        ]
    },
    math: {
        beginner: {
            pure_math: (count) => {
                const questions = [];
                for (let i = 0; i < count; i++) {
                    const op = Math.random() > 0.5 ? '+' : '-';
                    let a = Math.floor(Math.random() * (20 - 1 + 1)) + 1;
                    let b = Math.floor(Math.random() * (20 - 1 + 1)) + 1;
                    let ans;
                    if (op === '+') { ans = a + b; }
                    else {
                        if (a < b) [a, b] = [b, a];
                        ans = a - b;
                    }
                    const opts = new Set([ans]);
                    while (opts.size < 4) { opts.add(ans + Math.floor(Math.random() * (5 - (-5) + 1)) + (-5)); }
                    const optsArr = Array.from(opts).filter(n => n >= 0);
                    while (optsArr.length < 4) optsArr.push(Math.floor(Math.random() * (40 - 0 + 1)) + 0);
                    questions.push({ id: i, q: `${a} ${op} ${b} = ?`, options: optsArr.sort(() => Math.random() - 0.5), answer: ans.toString() });
                }
                return questions;
            },
            problems: (count) => {
                const templates = [
                    (a, b) => ({ q: `${a} ta olmangiz bor, do'stingiz ${b} ta berdi. Jami nechta?`, ans: a + b }),
                    (a, b) => ({ q: `Sizda ${a} dollar bor. ${b} dollar ishlatdingiz. Qancha qoldi?`, ans: a - b }),
                    (a, b) => ({ q: `Daraxtda ${a} qush bor. ${b} tasi uchib ketdi. Nechta qoldi?`, ans: a - b }),
                    (a, b) => ({ q: `${a} quti, har birida ${b} ta qalam bor. Jami nechta?`, ans: a * b }),
                ];
                return generateMathProblems(count, templates, 1, 10);
            }
        },
        intermediate: {
            pure_math: (count) => {
                const questions = [];
                for (let i = 0; i < count; i++) {
                    const type = Math.floor(Math.random() * (3 - 1 + 1)) + 1;
                    let qText, ans;
                    if (type === 1) { // Mult
                        let a = Math.floor(Math.random() * (15 - 2 + 1)) + 2; let b = Math.floor(Math.random() * (15 - 2 + 1)) + 2; qText = `${a} * ${b} = ?`; ans = a * b;
                    } else if (type === 2) { // Div
                        let b = Math.floor(Math.random() * (12 - 2 + 1)) + 2; let userAns = Math.floor(Math.random() * (12 - 2 + 1)) + 2; let a = b * userAns; qText = `${a} / ${b} = ?`; ans = userAns;
                    } else { // Mixed
                        let a = Math.floor(Math.random() * (50 - 10 + 1)) + 10; let b = Math.floor(Math.random() * (20 - 5 + 1)) + 5; let c = Math.floor(Math.random() * (10 - 2 + 1)) + 2; qText = `${a} - ${b} + ${c} = ?`; ans = a - b + c;
                    }
                    const opts = new Set([ans]);
                    while (opts.size < 4) opts.add(ans + Math.floor(Math.random() * (10 - (-10) + 1)) + (-10));
                    questions.push({ id: i, q: qText, options: Array.from(opts).sort(() => Math.random() - 0.5), answer: ans.toString() });
                }
                return questions;
            },
            problems: (count) => {
                const templates = [
                    (a, b) => ({ q: `Avtomobil ${a} km/soat tezlikda ${b} soat yurdi. Masofa qancha?`, ans: a * b }),
                    (a, b) => ({ q: `To'g'ri to'rtburchakning eni ${a}sm, bo'yi ${b}sm. Yuzi qancha?`, ans: a * b }),
                    (a, b) => ({ q: `${a} ta kitob ${b * a} so'm. Bitta kitob narxi qancha?`, ans: b }),
                    (a, b) => ({ q: `Do'kon ${a} ta olma sotdi, bu jami olmalarning 50%i edi. Jami nechta olma bor edi?`, ans: a * 2 }),
                ];
                return generateMathProblems(count, templates, 5, 20);
            }
        },
        advanced: {
            pure_math: (count) => {
                const questions = [];
                for (let i = 0; i < count; i++) {
                    const type = Math.floor(Math.random() * (4 - 1 + 1)) + 1;
                    let qText, ans;
                    if (type === 1) { let x = Math.floor(Math.random() * (12 - 2 + 1)) + 2; let a = Math.floor(Math.random() * (9 - 2 + 1)) + 2; let b = Math.floor(Math.random() * (20 - 1 + 1)) + 1; let c = a * x + b; qText = `${a}x + ${b} = ${c}. x = ?`; ans = x; }
                    else if (type === 2) { let p = Math.floor(Math.random() * (9 - 1 + 1)) + 1 * 10; let val = Math.floor(Math.random() * (20 - 2 + 1)) + 2 * 10; qText = `${val} ning ${p}% i nechchi?`; ans = (val * p) / 100; }
                    else { let d = Math.floor(Math.random() * (15 - 1 + 1)) + 1; qText = `${d} sonining ikkilik kodi qanday?`; ans = d.toString(2); }

                    const opts = new Set([ans]);
                    if (typeof ans === 'string') { while (opts.size < 4) { let fake = (Math.floor(Math.random() * (15 - 1 + 1)) + 1).toString(2); if (fake !== ans) opts.add(fake); } }
                    else { while (opts.size < 4) opts.add(ans + Math.floor(Math.random() * (5 - (-5) + 1)) + (-5)); }
                    questions.push({ id: i, q: qText, options: Array.from(opts).sort(() => Math.random() - 0.5), answer: ans.toString() });
                }
                return questions;
            },
            problems: (count) => {
                const templates = [
                    (a, b) => ({ q: `Poyezd ${a} mil/soat tezlikda ${b} soat yurdi. Jami masofa?`, ans: a * b }),
                    (a, b) => ({ q: `To'rtburchak yuzi ${a * b}, tomoni ${a}. Ikkinchi tomoni?`, ans: b }),
                ];
                return generateMathProblems(count, templates, 20, 100);
            }
        }
    },
    informatics: {
        beginner: [
            { q: "Kompyuterning 'miyasi' deb qaysi qism ataladi?", options: ["Monitor", "Klaviatura", "Protsessor", "Sichqoncha"], answer: "Protsessor", explanation: "Protsessor barcha hisob-kitoblarni bajaradi.", motivation: "Juda yaxshi!" },
            { q: "Sichqoncha (Mouse) qanday qurilma?", options: ["Kiritish qurilmasi", "Chiqarish qurilmasi", "Xotira", "Protsessor"], answer: "Kiritish qurilmasi", explanation: "Biz u orqali kompyuterga buyruq beramiz.", motivation: "Barakalla!" },
            { q: "Monitor nima uchun kerak?", options: ["Tasvirni ko'rsatish", "Ovoz chiqarish", "Yozish", "Hisoblash"], answer: "Tasvirni ko'rsatish", explanation: "Monitor tasvirni ekranga uzatadi.", motivation: "Juda yaxshi!" },
            { q: "Windows bu nima?", options: ["Operatsion tizim", "O'yin", "Antivirus", "Klaviatura"], answer: "Operatsion tizim", explanation: "Kompyuterni boshqaradigan dasturiy ta'minot.", motivation: "Ofarin!" },
            { q: "Qaysi biri axborot tashuvchi?", options: ["Fleshka", "Monitor", "Printer", "Klaviatura"], answer: "Fleshka", explanation: "Fleshka ma'lumot saqlaydi.", motivation: "To'g'ri!" },
            { q: "Paint dasturi nima uchun?", options: ["Rasm chizish", "Hisoblash", "Musiqa eshitish", "Internetga kirish"], answer: "Rasm chizish", explanation: "Sodda grafik muharrir.", motivation: "Ijodkor ekansiz!" },
            { q: "Klaviaturadan ma'lumot qanday kiritiladi?", options: ["Tugmalarni bosish orqali", "Ekranga qarab", "Gapirish orqali", "Sichqoncha bilan"], answer: "Tugmalarni bosish orqali", explanation: "Klaviatura tugmalardan iborat.", motivation: "Juda to'g'ri!" },
            { q: "Google nima?", options: ["Qidiruv tizimi", "O'yin", "Kompyuter modeli", "Antivirus"], answer: "Qidiruv tizimi", explanation: "Internetdan ma'lumot izlash uchun xizmat.", motivation: "Bilimdon!" },
            { q: "Printer vazifasi nima?", options: ["Qog'ozga chop etish", "Rasmga olish", "Ovoz yozish", "Internetga ulash"], answer: "Qog'ozga chop etish", explanation: "Ma'lumotni qog'ozga chiqaradi.", motivation: "Aniq!" },
            { q: "O'chirilgan fayllar qayerga tushadi?", options: ["Savatchaga (Recycle Bin)", "Internetga", "Fleshkaga", "Ekranga"], answer: "Savatchaga (Recycle Bin)", explanation: "O'chirilgan fayllar vaqtinchalik savatchada saqlanadi.", motivation: "E'tiborli bo'ling!" },
            { q: "Kompyuterni yoqish tugmasi qaysi?", options: ["Power", "Enter", "Esc", "Space"], answer: "Power", explanation: "Odatda maxsus belgi bilan ajralib turadi.", motivation: "Juda oddiy!" },
            { q: "Qaysi biri matn yozish dasturi?", options: ["Notepad", "Calculator", "Camera", "Player"], answer: "Notepad", explanation: "Eng sodda matn muharriri.", motivation: "To'g'ri!" },
            { q: "Space (Bo'sh joy) tugmasi nima qiladi?", options: ["So'zlar orasini ochadi", "O'chiradi", "Pastga tushiradi", "Dasturni yopadi"], answer: "So'zlar orasini ochadi", explanation: "Probel tashlaydi.", motivation: "Barakalla!" },
            { q: "Karnay (Speaker) nima qiladi?", options: ["Ovoz chiqaradi", "Rasm ko'rsatadi", "Yozadi", "Eshitadi"], answer: "Ovoz chiqaradi", explanation: "Audio ma'lumotni chiqarish qurilmasi.", motivation: "Aniq!" },
            { q: "Esc tugmasi nima uchun?", options: ["Chiqish yoki bekor qilish", "Kirish", "O'chirish", "Saqlash"], answer: "Chiqish yoki bekor qilish", explanation: "Escape - qochish, chiqish.", motivation: "To'g'ri!" },
            { q: "Kompyuter ekranidagi kichik rasmlar nima deyiladi?", options: ["Ikonkalar (Belgilar)", "Rasmlar", "Knopkalar", "Fayllar"], answer: "Ikonkalar (Belgilar)", explanation: "Dastur yoki fayl belgisi.", motivation: "Juda to'g'ri!" },
            { q: "Caps Lock tugmasi nima qiladi?", options: ["Katta harfda yozadi", "Ovozni o'chiradi", "Kompyuterni o'chiradi", "Internetni yoqadi"], answer: "Katta harfda yozadi", explanation: "Harflarni yuqori registrga o'tkazadi.", motivation: "Barakalla!" },
            { q: "Eng mashhur matn muharriri?", options: ["Microsoft Word", "Excel", "Photoshop", "Paint"], answer: "Microsoft Word", explanation: "Hujjatlar bilan ishlash uchun standart.", motivation: "To'g'ri!" },
            { q: "Kompyuterga ovoz kiritish qurilmasi?", options: ["Mikrofon", "Karnay", "Monitor", "Printer"], answer: "Mikrofon", explanation: "Ovozni yozib oladi.", motivation: "Aniq!" },
            { q: "Faylni saqlash uchun qaysi tugmalar bosiladi?", options: ["Ctrl + S", "Ctrl + C", "Ctrl + V", "Alt + F4"], answer: "Ctrl + S", explanation: "S - Save (Saqlash).", motivation: "Foydali bilim!" },
            { q: "Excel dasturi nima uchun?", options: ["Jadvallar bilan ishlash", "Rasm chizish", "Musiqa", "Video"], answer: "Jadvallar bilan ishlash", explanation: "Hisob-kitob va jadvallar ustasi.", motivation: "Ofarin!" },
            { q: "Qaysi biri operatsion tizim emas?", options: ["Microsoft Word", "Windows", "Linux", "MacOS"], answer: "Microsoft Word", explanation: "Word bu dastur, tizim emas.", motivation: "To'g'ri ajratdingiz!" },
            { q: "Shift tugmasi nima qiladi?", options: ["Harfni vaqtincha katta qiladi", "O'chiradi", "Saqlaydi", "Chiqadi"], answer: "Harfni vaqtincha katta qiladi", explanation: "Yoki belgilarni o'zgartiradi.", motivation: "Yaxshi!" },
            { q: "Internetga kirish uchun nima kerak?", options: ["Brauzer", "Printer", "Word", "Paint"], answer: "Brauzer", explanation: "Chrome, Edge yoki Firefox kabi dastur.", motivation: "To'g'ri!" },
            { q: "Web-kamera nima qiladi?", options: ["Video tasvirga oladi", "Ovoz chiqaradi", "Chop etadi", "Yozadi"], answer: "Video tasvirga oladi", explanation: "Video qo'ng'iroqlar uchun.", motivation: "Aniq!" },
            { q: "Notebook nima?", options: ["Ixcham kompyuter (Noutbuk)", "Telefon", "Televizor", "Soat"], answer: "Ixcham kompyuter (Noutbuk)", explanation: "Olib yurishga qulay kompyuter.", motivation: "Oddiy!" },
            { q: "Papka (Folder) nima uchun kerak?", options: ["Fayllarni tartiblash uchun", "Rasm chizish uchun", "Musiqa eshitish uchun", "O'yin o'ynash uchun"], answer: "Fayllarni tartiblash uchun", explanation: "Fayllarni guruhlash vositasi.", motivation: "Tartib muhim!" },
            { q: "Delete tugmasi nima qiladi?", options: ["O'chiradi", "Yozadi", "Saqlaydi", "Nusxalaydi"], answer: "O'chiradi", explanation: "Tanlangan obyektni o'chiradi.", motivation: "Ehtiyot bo'ling!" },
            { q: "Touchpad qayerda bo'ladi?", options: ["Noutbukda", "Stol kompyuterida", "Televizorda", "Radioda"], answer: "Noutbukda", explanation: "Sichqoncha o'rnini bosuvchi panel.", motivation: "Bilimdon!" }
        ],
        intermediate: [
            { q: "1 Bayt necha bitga teng?", options: ["8", "10", "2", "1024"], answer: "8", explanation: "1 Bayt = 8 bit.", motivation: "Asoslarni bilasiz!" },
            { q: "RAM so'zining ma'nosi?", options: ["Tezkor xotira", "Doimiy xotira", "Qattiq disk", "Fleshka"], answer: "Tezkor xotira", explanation: "Random Access Memory - vaqtinchalik xotira.", motivation: "Mukkamal!" },
            { q: "IP manzil nima?", options: ["Kompyuter manzili", "Email", "Login", "Parol"], answer: "Kompyuter manzili", explanation: "Internet Protocol address - tarmoqdagi manzil.", motivation: "Davom eting!" },
            { q: "Wi-Fi nima?", options: ["Simsiz tarmoq", "Antivirus", "O'yin", "Fleshka"], answer: "Simsiz tarmoq", explanation: "Wireless Fidelity.", motivation: "Zamonaviy!" },
            { q: "Brauzerga misol?", options: ["Chrome", "Word", "Excel", "Paint"], answer: "Chrome", explanation: "Veb sahifalarni ko'rish dasturi.", motivation: "To'g'ri!" },
            { q: ".docx qaysi dastur fayli?", options: ["Word", "Excel", "PowerPoint", "Paint"], answer: "Word", explanation: "Matn muharriri fayl formati.", motivation: "Ofarin!" },
            { q: "Kompyuter virusi nima?", options: ["Zararli dastur", "Bakteriya", "Chang", "O'yin"], answer: "Zararli dastur", explanation: "Kompyuter ishini buzuvchi dastur.", motivation: "Xavfsizlik muhim!" },
            { q: "Internet tarmog'ining eng katta qismi nima?", options: ["WWW (World Wide Web)", "Facebook", "Telegram", "Google"], answer: "WWW (World Wide Web)", explanation: "Butunjahon o'rgimchak to'ri.", motivation: "Dunyoqarash keng!" },
            { q: "Email nima?", options: ["Elektron pochta", "Oddiy xat", "SMS", "Telefon"], answer: "Elektron pochta", explanation: "Electronic Mail - xat almashish xizmati.", motivation: "To'g'ri!" },
            { q: "Klaviatura qanday qurilma?", options: ["Kiritish", "Chiqarish", "Xotira", "Markaziy"], answer: "Kiritish", explanation: "Ma'lumot kiritish uchun xizmat qiladi.", motivation: "Barakalla!" },
            { q: "CPU qisqartmasi ma'nosi?", options: ["Central Processing Unit", "Central Power Unit", "Computer Personal Unit", "Control Panel Utility"], answer: "Central Processing Unit", explanation: "Markaziy Protsessor.", motivation: "Qiyin atama, ofarin!" },
            { q: "SSD va HDD farqi?", options: ["SSD tezroq", "HDD tezroq", "Farqi yo'q", "SSD faqat o'yin uchun"], answer: "SSD tezroq", explanation: "Solid State Drive mexanik qismlarsiz ishlaydi.", motivation: "Zamonaviy bilim!" },
            { q: "Brauzerda 'History' nima?", options: ["Kirilgan saytlar tarixi", "Tarix fani", "O'chirilgan fayllar", "Parollar"], answer: "Kirilgan saytlar tarixi", explanation: "Siz kirgan veb-sahifalar ro'yxati.", motivation: "To'g'ri!" },
            { q: "Ctrl + C nimani bajaradi?", options: ["Nusxa oladi (Copy)", "Qirqib oladi (Cut)", "Qo'yadi (Paste)", "Chop etadi (Print)"], answer: "Nusxa oladi (Copy)", explanation: "Mashhur klaviatura kombinatsiyasi.", motivation: "Tezkor usul!" },
            { q: "Monitorning o'lchami nimalarda o'lchanadi?", options: ["Dyuym", "Metr", "Kilogramm", "Litr"], answer: "Dyuym", explanation: "Ekran diagonali dyuymda o'lchanadi.", motivation: "Aniq o'lchov!" },
            { q: "PDF qanday format?", options: ["Hujjat formati", "Video format", "Audio format", "Dastur"], answer: "Hujjat formati", explanation: "Portable Document Format.", motivation: "To'g'ri!" },
            { q: "LAN nima?", options: ["Mahalliy tarmoq", "Global tarmoq", "Wi-Fi", "Fleshka"], answer: "Mahalliy tarmoq", explanation: "Local Area Network - kichik xududdagi tarmoq.", motivation: "Tarmoq ustasi!" },
            { q: "1 Terabayt (TB) qancha?", options: ["1024 Gigabayt (GB)", "1000 Megabayt", "100 GB", "10 GB"], answer: "1024 Gigabayt (GB)", explanation: "Katta hajmdagi ma'lumot birligi.", motivation: "Katta sonlar!" },
            { q: "Qaysi biri grafik muharrir?", options: ["Photoshop", "Excel", "Notepad", "Calculator"], answer: "Photoshop", explanation: "Rasmlar bilan ishlash dasturi.", motivation: "Ijodiy javob!" },
            { q: "Server nima?", options: ["Xizmat ko'rsatuvchi kuchli kompyuter", "Oddiy sichqoncha", "O'yin", "Monitor"], answer: "Xizmat ko'rsatuvchi kuchli kompyuter", explanation: "Tarmoqda ma'lumot va xizmatlarni taqdim etadi.", motivation: "Juda yaxshi!" },
            { q: "Bulutli texnologiya (Cloud) nima?", options: ["Internetdagi xotira va xizmatlar", "Yomg'ir buluti", "Kompyuterdagi ventilyator", "Yangi o'yin"], answer: "Internetdagi xotira va xizmatlar", explanation: "Ma'lumotlarni masofada saqlash.", motivation: "Zamonaviy!" },
            { q: "Shortcut (Yorliq) nima?", options: ["File yoki dasturga yo'l ko'rsatuvchi", "Virus", "Papka", "O'chirilgan fayl"], answer: "File yoki dasturga yo'l ko'rsatuvchi", explanation: "Tez kirish uchun havola.", motivation: "To'g'ri!" },
            { q: "Task Manager (Vazifalar menejeri) nima uchun?", options: ["Ishlayotgan dasturlarni ko'rish va boshqarish", "Fayl yaratish", "Rasm chizish", "O'yin o'ynash"], answer: "Ishlayotgan dasturlarni ko'rish va boshqarish", explanation: "Qotib qolgan dasturlarni yopish mumkin.", motivation: "Tizim ma'muri!" },
            { q: "Zip fayl nima?", options: ["Arxivlangan (siqilgan) fayl", "Buzilgan fayl", "Virus", "Musiqa"], answer: "Arxivlangan (siqilgan) fayl", explanation: "Hajmini kichraytirish uchun arxivlanadi.", motivation: "Zo'r!" },
            { q: "VPN nima?", options: ["Virtual Xususiy Tarmoq", "Yangi brauzer", "Tezkor internet", "Antivirus"], answer: "Virtual Xususiy Tarmoq", explanation: "Virtual Private Network - anonimlik va xavfsizlik uchun.", motivation: "Xavfsizlik!" },
            { q: "IP manzil necha qismdan iborat (IPv4)?", options: ["4 qismdan", "2 qismdan", "6 qismdan", "10 qismdan"], answer: "4 qismdan", explanation: "Masalan: 192.168.1.1", motivation: "Aniq!" },
            { q: "Megabayt (MB) va Gigabayt (GB) - qaysi katta?", options: ["GB katta", "MB katta", "Teng", "Bilmayman"], answer: "GB katta", explanation: "1 GB = 1024 MB.", motivation: "To'g'ri hisob!" },
            { q: "Modem nima vazifani bajaradi?", options: ["Internetga ulaydi", "Rasmni chop etadi", "Ovozni yozadi", "Sovutadi"], answer: "Internetga ulaydi", explanation: "Signallarni o'zgartirib beradi.", motivation: "Aloqachi!" },
            { q: "Drayver (Driver) nima?", options: ["Qurilmani boshqaruvchi dastur", "Haydovchi", "O'yin", "Virus"], answer: "Qurilmani boshqaruvchi dastur", explanation: "Qurilma va tizim o'rtasidagi ko'prik.", motivation: "Dasturiy bilim!" }
        ],
        advanced: [
            { q: "Algoritm nima?", options: ["Ketma-ketlik", "Dastur kodi", "Kompyuter qismi", "O'yin"], answer: "Ketma-ketlik", explanation: "Vazifani bajarish uchun aniq qadamlar.", motivation: "Dasturchi bo'lasiz!" },
            { q: "Python da 'print()' nima qiladi?", options: ["Ekranga chiqaradi", "Hisoblaydi", "O'chiradi", "Saqlaydi"], answer: "Ekranga chiqaradi", explanation: "Ma'lumotni konsolga chop etadi.", motivation: "Kodlashni bilasiz!" },
            { q: "HTML nimani anglatadi?", options: ["Hyper Text Markup Language", "High Tech Made Language", "Home Tool Markup Language", "Hyper Text Made Link"], answer: "Hyper Text Markup Language", explanation: "Veb sahifalarni belgilash tili.", motivation: "Ajoyib bilim!" },
            { q: "Qaysi biri dasturlash tili emas?", options: ["HTML", "Python", "C++", "Java"], answer: "HTML", explanation: "HTML - belgilash tili, dasturlash tili emas.", motivation: "Chuqur bilim!" },
            { q: "DDoS hujum nima?", options: ["Serverga hujum", "Antivirus", "O'yin", "Dastur"], answer: "Serverga hujum", explanation: "Distributed Denial of Service.", motivation: "Kiberxavfsizlik!" },
            { q: "Binary sanoq tizimi raqamlari?", options: ["0 va 1", "1 va 2", "0 dan 9 gacha", "A va B"], answer: "0 va 1", explanation: "Ikkilik sanoq tizimi.", motivation: "Kompyuter tili!" },
            { q: "URL nima?", options: ["Veb-sahifa manzili", "Kompyuter nomi", "Fayl turi", "Antivirus"], answer: "Veb-sahifa manzili", explanation: "Uniform Resource Locator.", motivation: "Internet ustasi!" },
            { q: "Python-da sikl (takrorlash) operatori?", options: ["for", "if", "print", "input"], answer: "for", explanation: "'for' yoki 'while' sikl uchun ishlatiladi.", motivation: "Dasturlash sirlari!" },
            { q: "Phishing nima?", options: ["Firibgarlik turi", "O'yin", "Baliq ovlash", "Antivirus"], answer: "Firibgarlik turi", explanation: "Ma'lumotlarni o'g'irlash usuli.", motivation: "Hushyor bo'ling!" },
            { q: "Sun'iy intellekt (AI) nima?", options: ["Inson kabi fikrlaydigan dastur", "Oddiy kalkulyator", "Rasm chizish dasturi", "O'yin"], answer: "Inson kabi fikrlaydigan dastur", explanation: "Murakkab masalalarni yechuvchi tizim.", motivation: "Kelajak texnologiyasi!" },
            { q: "Firewall nima?", options: ["Tarmoq xavfsizligi tizimi", "Yong'in o'chirish", "O'yin rejimi", "Antivirus"], answer: "Tarmoq xavfsizligi tizimi", explanation: "Ruxsatsiz kirishdan himoya qiladi (Xavfsizlik devori).", motivation: "Xavfsizlik birinchi o'rinda!" },
            { q: "Bug (Bag) nima?", options: ["Dasturdagi xatolik", "Kompyuter qismi", "Yangi dastur", "Foydali funksiya"], answer: "Dasturdagi xatolik", explanation: "Kodlashdagi nuqson.", motivation: "Dasturchilar atamasi!" },
            { q: "Open Source nima?", options: ["Ochiq kodli dasturiy ta'minot", "Bepul internet", "Ochiq eshik", "Yangi operatsion tizim"], answer: "Ochiq kodli dasturiy ta'minot", explanation: "Kodi hamma uchun ochiq va o'zgartirilishi mumkin.", motivation: "Erkinlik!" },
            { q: "Blockchain nima?", options: ["Markazlashmagan ma'lumotlar bazasi", "Yangi pul birligi", "O'yin", "Ijtimoiy tarmoq"], answer: "Markazlashmagan ma'lumotlar bazasi", explanation: "Bloklar zanjiri texnologiyasi.", motivation: "Kripto olami!" },
            { q: "HTTP va HTTPS farqi?", options: ["HTTPS xavfsizroq (shifrlangan)", "HTTP tezroq", "Farqi yo'q", "HTTPS faqat pullik"], answer: "HTTPS xavfsizroq (shifrlangan)", explanation: "S - Secure (Xavfsiz) degani.", motivation: "Xavfsizlik muhim!" },
            { q: "IoT (Internet of Things) nima?", options: ["Buyumlar interneti", "Tezkor internet", "Faqat kompyuterlar tarmog'i", "Yangi o'yin"], answer: "Buyumlar interneti", explanation: "Aqlli qurilmalarning o'zaro bog'lanishi.", motivation: "Kelajak!" },
            { q: "Big Data nima?", options: ["Katta hajmdagi ma'lumotlar", "Katta kompyuter", "Uzun kod", "Katta fleshka"], answer: "Katta hajmdagi ma'lumotlar", explanation: "Tahlil qilish uchun ulkan ma'lumotlar to'plami.", motivation: "Global fikr!" },
            { q: "SQL nima?", options: ["Ma'lumotlar bazasi tili", "Operatsion tizim", "O'yin", "Grafik muharrir"], answer: "Ma'lumotlar bazasi tili", explanation: "Structured Query Language.", motivation: "Ma'lumotlar ustasi!" },
            { q: "Qaysi biri Frontend tili?", options: ["JavaScript", "Python", "C++", "Java"], answer: "JavaScript", explanation: "Vebning ko'rinish qismi uchun javobgar.", motivation: "Veb dasturchi!" },
            { q: "ASCII nima?", options: ["Belgilarni kodlash standarti", "Dasturlash tili", "Kompyuter modeli", "Antivirus"], answer: "Belgilarni kodlash standarti", explanation: "American Standard Code for Information Interchange.", motivation: "Kodlash asoslari!" },
            { q: "Troyan (Trojan) nima?", options: ["Foydali bo'lib ko'ringan virus", "Yaxshi dastur", "Antivirus", "Brauzer"], answer: "Foydali bo'lib ko'ringan virus", explanation: "Ichida zararli kod yashiringan dastur.", motivation: "Ehtiyotkorlik!" },
            { q: "Shifrlash (Encryption) nima?", options: ["Ma'lumotni maxfiylashtirish", "Ma'lumotni o'chirish", "Faylni ochish", "Nusxalash"], answer: "Ma'lumotni maxfiylashtirish", explanation: "O'qish imkonsiz holga keltirish.", motivation: "Maxfiylik!" },
            { q: "BIOS vazifasi nima?", options: ["Tizimni ishga tushirish va tekshirish", "Internetga kirish", "O'yin o'ynash", "Matn yozish"], answer: "Tizimni ishga tushirish va tekshirish", explanation: "Basic Input/Output System.", motivation: "Tizim yuragi!" },
            { q: "Qaysi biri yuqori darajali til?", options: ["Python", "Assembly", "Machine Code", "Binary"], answer: "Python", explanation: "Inson tiliga yaqin dasturlash tili.", motivation: "To'g'ri!" },
            { q: "Pixel (Piksel) nima?", options: ["Tasvirning eng kichik nuqtasi", "Katta rasm", "Ovoz bo'lagi", "Fayl"], answer: "Tasvirning eng kichik nuqtasi", explanation: "Ekrani tashkil etuvchi nuqta.", motivation: "Grafik bilim!" },
            { q: "Hacker kim?", options: ["Tizim zaifligini topuvchi mutaxassis", "Kompyuter ustasi", "O'yinchi", "Sotuvchi"], answer: "Tizim zaifligini topuvchi mutaxassis", explanation: "Oq yoki qora niyetli bo'lishi mumkin.", motivation: "Qiziq!" },
            { q: "API nima?", options: ["Dasturlararo aloqa interfeysi", "Yangi dastur", "O'yin", "Operatsion tizim"], answer: "Dasturlararo aloqa interfeysi", explanation: "Application Programming Interface.", motivation: "Dasturchi!" },
            { q: "Cookie nima (Brauzerda)?", options: ["Sayt tomonidan saqlanadigan kichik fayl", "Shirinlik", "Virus", "Rasm"], answer: "Sayt tomonidan saqlanadigan kichik fayl", explanation: "Foydalanuvchi sozlamalarini eslab qolish uchun.", motivation: "Web bilim!" },
            { q: "Qaysi biri mobil operatsion tizim?", options: ["Android", "Windows 10", "MacOS", "Linux"], answer: "Android", explanation: "Smartfonlar uchun eng keng tarqalgan tizim.", motivation: "Mobil texnologiya!" }
        ]
    },
    uzbek: {
        beginner: {
            grammar: [
                ["'Kitob' so'zining ko'pligi:", "Kitoblar", "Kitob", "Kitobim", "Kitobing"],
                ["Qaysi so'z to'g'ri yozilgan?", "Maktab", "Maktap", "Maqtab", "Mactab"],
                ["O'zbek alifbosida nechta harf bor?", "29", "26", "28", "30"],
                ["'Ona' so'zining sinonimi:", "Volida", "Ota", "Aka", "Singil"],
                ["'Oq' so'zining teskarisi:", "Qora", "Qizil", "Sariq", "Ko'k"],
                ["Gap nimadan boshlanadi?", "Katta harfdan", "Kichik harfdan", "Nuqtadan", "Vergildan"],
                ["So'rog' gap oxiriga nima qo'yiladi?", "?", "!", ".", ","],
                ["'Uy' so'ziga qaysi qo'shimcha to'g'ri?", "Uyga", "Uyg'a", "Uyda", "Uyni"],
                ["'Men' so'zining egalik shakli:", "Mening", "Sening", "Uning", "Bizning"],
                ["'Qalam' so'zi qanday so'z turkumi?", "Ot", "Fe'l", "Sifat", "Son"],
                ["'Yozmoq' fe'lining buyruq shakli:", "Yoz", "Yozdi", "Yozadi", "Yozgan"],
                ["O'zbek tili qaysi til oilasiga kiradi?", "Turkiy", "Forsiy", "Slavyan", "Arab"],
                ["'Non' so'zining sifatdoshi:", "Nonvoy", "Nonli", "Nonday", "Non"],
                ["'O'quvchi' so'zining o'zagi:", "O'qi", "O'quv", "O'quvchi", "O'qish"],
                ["Tovushlar nimalarga bo'linadi?", "Unli va Undosh", "Katta va Kichik", "Qattiq va Yumshoq", "Ochiq va Yopiq"],
                ["Eng mashhur o'zbek taomi?", "Palov", "Manti", "Somsa", "Sho'rva"],
                ["'Daftar' so'zi qayerdan kirib kelgan?", "Arab-Fors", "Rus", "Ingliz", "Xitoy"],
                ["Alifboda birinchi harf?", "A", "B", "O", "D"],
                ["'Bolalar' so'zida nechta bo'g'in bor?", "3", "2", "4", "1"],
                ["Ega va kesim nima deyiladi?", "Bosh bo'laklar", "Ikkinchi darajali", "Uyushgan", "Yordamchi"]
            ],
            literature: [
                ["Alisher Navoiy qachon tug'ilgan?", "1441", "1440", "1483", "1501"],
                ["'Xamsa' kimning asari?", "Navoiy", "Bobur", "Qodiriy", "Cho'lpon"],
                ["O'zbekiston madhiyasi muallifi:", "Abdulla Oripov", "Erkin Vohidov", "Hamid Olimjon", "Zulfiya"],
                ["'O'tkan kunlar' asari janri:", "Roman", "Qissa", "Hikoya", "She'r"],
                ["Bobur qayerda tug'ilgan?", "Andijon", "Samarqand", "Buxoro", "Toshkent"],
                ["'Sariq devni minib' asari muallifi:", "Xudoyberdi To'xtaboyev", "Oybek", "G'afur G'ulom", "Abdulla Qahhor"],
                ["Zulfiya kim?", "Shoira", "Yozuvchi", "Olim", "Rassom"],
                ["'Shum bola' asari muallifi:", "G'afur G'ulom", "Oybek", "Qodiriy", "Navoiy"],
                ["Navoiyning do'sti kim bo'lgan?", "Husayn Boyqaro", "Bobur", "Temur", "Ulug'bek"],
                ["Abdulla Qodiriy qaysi asarni yozgan?", "O'tkan kunlar", "Xamsa", "Boburnoma", "Mehrobdan chayon"]
            ]
        },
        intermediate: {
            grammar: [
                ["Fe'lning zamonlari nechta?", "3", "2", "4", "5"],
                ["Qaysi biri sifat?", "Chiroyli", "Yozmoq", "Kitob", "Ikki"],
                ["Egalik qo'shimchalari nechta shaxsda bo'ladi?", "3", "2", "1", "4"],
                ["Kelishiklar soni nechta?", "6", "5", "7", "4"],
                ["'Chiroyli' so'zining antonimi:", "Xunuk", "Go'zal", "Korkam", "Badbashara"],
                ["'Yugurmoq' so'zining o'tgan zamoni:", "Yugurdi", "Yuguryapti", "Yuguradi", "Yugurmoqchi"],
                ["Ravish so'roqlari:", "Qanday? Qay holatda?", "Kim? Nima?", "Qancha?", "Qachon?"],
                ["Undalma qanday tinish belgisi bilan ajratiladi?", "Vergul", "Nuqta", "Tire", "Ikki nuqta"],
                ["'Temir' so'zining sifatdoshi:", "Temirchi", "Temirday", "Temirli", "Temir"],
                ["Sifat darajalari nechta?", "4", "3", "2", "5"]
            ],
            literature: [
                ["'Boburnoma' qanday asar?", "Tarixiy-memuar", "Roman", "Doston", "Qissa"],
                ["Alisher Navoiy qayerda vafot etgan?", "Hirot", "Samarqand", "Buxoro", "Dellhi"],
                ["Abdulla Oripov qachon tug'ilgan?", "1941", "1950", "1960", "1930"],
                ["'Kecha va kunduz' asari muallifi:", "Cho'lpon", "Fitrat", "Behbudiy", "Qodiriy"],
                ["O'zbek tiliga davlat tili maqomi qachon berilgan?", "1989", "1991", "1990", "1992"],
                ["Alpomish dostoni qanday doston?", "Qahramonlik", "Ishqiy", "Tarixiy", "Fantastik"],
                ["'Mehrobdan chayon' asari qahramoni:", "Anvar", "Otabek", "Mirzo", "Qorabo'yin"],
                ["Oybekning mashhur romani:", "Navoiy", "Bobur", "Temur", "Ulug'bek"],
                ["Erkin Vohidovning asari:", "O'zbegim", "O'zbekiston", "Vatan", "Ona"],
                ["Hamid Olimjon nima deb atalgan?", "Baxt va shodlik kuychisi", "G'azal mulkining sultoni", "Xalq shoiri", "Dramaturg"]
            ]
        },
        advanced: {
            grammar: [
                ["Uyushgan bo'laklar orasida qanday tinish belgisi qo'yiladi?", "Vergul", "Tire", "Nuqta", "Nuqtali vergul"],
                ["Bog'lovchilar necha turga bo'linadi?", "2", "3", "4", "5"],
                ["Holning ma'no turlari nechta?", "6", "5", "4", "7"],
                ["Kirish so'zlar gapda qanday vazifa bajaradi?", "Gap bo'lagi bo'lmaydi", "Ega", "Kesim", "Hol"],
                ["Qaysi gapda tinish belgisi xato qo'yilgan?", "Men keldim, ammo u yo'q.", "Men keldim ammo, u yo'q.", "Men, keldim.", "U - talaba."],
                ["Murakkab qo'shma gap turlari:", "3", "2", "4", "5"],
                ["Qaysi biri modal so'z?", "Ehtimol", "Chunki", "Va", "Lekin"],
                ["Imlo qoidalariga ko'ra qaysi so'z xato?", "Toshkenttta", "Toshkentda", "Maktabda", "Shaharda"],
                ["Ibora deb nimaga aytiladi?", "Ko'chma ma'noli turg'un birikma", "So'z birikmasi", "Gap", "Qo'shma so'z"],
                ["'Oltin kuz' birikmasidagi 'oltin' so'zi qanday ma'noda?", "Ko'chma", "O'z", "Termin", "Atama"]
            ],
            literature: [
                ["Navoiyning birinchi devoni:", "Badoye-ul Bidoya", "Xazoyin-ul Maoniy", "Navodir-ush Shabab", "Favoyid-ul Kibar"],
                ["'Qutadg'u bilig' asari muallifi:", "Yusuf Xos Hojib", "Ahmad Yugnakiy", "Qoshg'ariy", "Navoiy"],
                ["'Devonu lug'otit turk' kimning asari?", "Mahmud Qoshg'ariy", "Yusuf Xos Hojib", "Ahmad Yassaviy", "Lutfiy"],
                ["Atoyi qaysi davr shoiri?", "XV asr", "XIV asr", "XIII asr", "XVI asr"],
                ["Mashrab qanday shoir?", "Isyonkor", "Saray shoiri", "Tarixchi", "Nosir"],
                ["Ogahiy qaysi xonlikda yashagan?", "Xiva", "Qo'qon", "Buxoro", "Samarqand"],
                ["Fitratning mashhur dramasi:", "Abulfayzxon", "Padarkush", "Zaharli hayot", "Boy ila xizmatchi"],
                ["Abdulla Qahhorning laqabi:", "O'zbek chexovi", "G'azal sultoni", "Nasr ustasi", "Dramaturg"],
                ["Mirtemir qaysi asari bilan mashhur?", "Surat", "O'zbekiston", "Ona", "Vatan"],
                ["Odil Yoqubovning romani:", "Ulug'bek xazinasi", "Yulduzli tunlar", "Avlodlar dovoni", "Sohibqiron"]
            ]
        }
    },
    history: {
        beginner: [
            { q: "Amir Temur nechanchi yilda tug'ilgan?", a: "1336", o: ["1337", "1441", "1340"], e: "Amir Temur 1336-yil Shahrisabzda tug'ilgan." },
            { q: "O'zbekiston mustaqillikka qachon erishgan?", a: "1991", o: ["1989", "1992", "1990"], e: "1991-yil 31-avgust." },
            { q: "Alisher Navoiyning mashhur asari?", a: "Xamsa", o: ["Boburnoma", "Qutadg'u bilig", "Zarbulmasal"], e: "Xamsa - 5 doston." },
            { q: "Ulug'bek rasadxonasi qayerda?", a: "Samarqand", o: ["Buxoro", "Xiva", "Toshkent"], e: "Samarqandda joylashgan." },
            { q: "Somoniylar davlati poytaxti?", a: "Buxoro", o: ["Samarqand", "Marv", "Urganch"], e: "Poytaxt Buxoro bo'lgan." },
            { q: "Bobur qaysi asarni yozgan?", a: "Boburnoma", o: ["Xamsa", "Shohnoma", "Devon"], e: "Mashhur memuar asar." },
            { q: "Jaloliddin Manguberdi kimga qarshi kurashgan?", a: "Chingizxon", o: ["Amir Temur", "Iskandar Zulqarnayn", "Kir"], e: "Mo'g'ullarga qarshi." },
            { q: "Toshkent qachon poytaxt bo'ldi?", a: "1930", o: ["1924", "1991", "1865"], e: "1930-yilda ko'chirilgan." },
            { q: "Spitamen kimga qarshi kurashgan?", a: "Makedoniyalik Iskandar", o: ["Doro", "Chingizxon", "Eron"], e: "Yunonlarga qarshi." },
            { q: "Mang'itlar sulolasi qayerda hukmronlik qilgan?", a: "Buxoro Amirligi", o: ["Xiva Xonligi", "Qo'qon Xonligi", "Temuriylar"], e: "Buxoroda." },
            { q: "O'zbekiston bayrog'i qachon qabul qilingan?", a: "1991", o: ["1992", "1990", "1993"], e: "1991-yil 18-noyabr." },
            { q: "Konstitutsiya kuni qachon?", a: "8-dekabr", o: ["1-sentyabr", "14-yanvar", "21-mart"], e: "8-dekabr 1992-yil." },
            { q: "O'zbekistonning birinchi prezidenti?", a: "I.Karimov", o: ["Sh.Mirziyoyev", "Y.Oxunboboyev", "F.Xo'jayev"], e: "Islom Karimov." },
            { q: "Navoiy qachon tug'ilgan?", a: "1441", o: ["1440", "1483", "1500"], e: "1441-yil 9-fevral." },
            { q: "Bobur qachon tug'ilgan?", a: "1483", o: ["1441", "1336", "1530"], e: "1483-yil 14-fevral." }
        ],
        intermediate: [
            { q: "Ikkinchi jahon urushi qachon boshlangan?", a: "1939", o: ["1941", "1945", "1914"], e: "1939-yil 1-sentyabr." },
            { q: "Piramidalar qayerda joylashgan?", a: "Misr", o: ["Sudan", "Meksika", "Xitoy"], e: "Gizadagi piramidalar." },
            { q: "Rim imperiyasi qachon qulagan?", a: "476", o: ["1453", "1000", "395"], e: "G'arbiy Rim 476-yilda." },
            { q: "Napoleon Bonapart qaysi davlat imperatori edi?", a: "Fransiya", o: ["Angliya", "Germaniya", "Italiya"], e: "Fransiya imperatori." },
            { q: "Birinchi odam oyga qachon qadam qo'ygan?", a: "1969", o: ["1961", "1975", "1957"], e: "Neil Armstrong 1969-yil." },
            { q: "Buyuk ipak yo'li qayerdan boshlangan?", a: "Xitoy", o: ["Hindiston", "Rim", "Eron"], e: "Xitoyning Sian shahridan." },
            { q: "Amerikani kim kashf etgan?", a: "Xristofor Kolumb", o: ["Vasko da Gama", "Magellan", "Kuk"], e: "1492-yilda." },
            { q: "Titanic qachon cho'kkan?", a: "1912", o: ["1905", "1920", "1899"], e: "1912-yil aprel." },
            { q: "Temir xotin laqabli siyosatchi?", a: "Margaret Tetcher", o: ["Indira Gandi", "Merkel", "Qirolicha Viktoriya"], e: "Buyuk Britaniya Bosh vaziri." },
            { q: "Eng uzun daryo?", a: "Nil", o: ["Amazonka", "Volga", "Amudaryo"], e: "Nil daryosi." },
            { q: "Birinchi jahon urushi qachon boshlangan?", a: "1914", o: ["1918", "1939", "1941"], e: "1914-yil." },
            { q: "SSSR qachon tarqalib ketgan?", a: "1991", o: ["1989", "1990", "1985"], e: "1991-yil dekabr." },
            { q: "Berlin devori qachon qulagan?", a: "1989", o: ["1991", "1961", "1945"], e: "1989-yil." },
            { q: "Chingizxon qachon vafot etgan?", a: "1227", o: ["1220", "1219", "1250"], e: "1227-yil." },
            { q: "Hindiston mustaqilligi qachon?", a: "1947", o: ["1950", "1945", "1960"], e: "1947-yil." }
        ],
        advanced: [
            { q: "Yuz yillik urush kimlar o'rtasida bo'lgan?", a: "Angliya va Fransiya", o: ["Rim va Karfagen", "Germaniya va Rossiya", "AQSH va Yaponiya"], e: "1337-1453 yillar." },
            { q: "Magna Carta qachon imzolangan?", a: "1215", o: ["1066", "1492", "1776"], e: "1215-yil Angliyada." },
            { q: "AQSH mustaqillik deklaratsiyasi qachon?", a: "1776", o: ["1789", "1865", "1900"], e: "1776-yil 4-iyul." },
            { q: "Fransuz inqilobi qachon boshlangan?", a: "1789", o: ["1812", "1848", "1917"], e: "1789-yil Bastiliya olinishi bilan." },
            { q: "Konstantinopol qachon fath etilgan?", a: "1453", o: ["1492", "1204", "1071"], e: "Usmonlilar tomonidan 1453-yil." },
            { q: "Versal sulh shartnomasi qachon imzolangan?", a: "1919", o: ["1918", "1945", "1939"], e: "1-jahon urushidan keyin." },
            { q: "BMT qachon tashkil topgan?", a: "1945", o: ["1948", "1950", "1919"], e: "1945-yil." },
            { q: "NATO qachon tuzilgan?", a: "1949", o: ["1955", "1945", "1991"], e: "1949-yil." },
            { q: "Karib inqirozi qachon bo'lgan?", a: "1962", o: ["1950", "1970", "1980"], e: "1962-yil Kuba." },
            { q: "Chernobil halokati qachon yuz bergan?", a: "1986", o: ["1990", "1979", "2000"], e: "1986-yil 26-aprel." }
        ]
    }
};



